Repository OpenBB-finance/openbb-docs, pull requests merged in 2024-11, with the labels that each got.

#24 Add Error Section To Platform FAQ & Update Extensions Page.
  content/platform/developer_guide/extensions.mdx
  content/platform/faqs/errors.mdx
  content/platform/faqs/index.mdx
  content/platform/installation.mdx
  content/platform/user_guides/extensions.mdx
Labels: documentation

#40 fix widgets path and fix security
  docusaurus.config.ts
  scripts/generate_widgets_library.py
Labels: security, p2

#41 [Security] Update packages for Dependabot.
  package-lock.json
  package.json
  yarn.lock
Labels: security

#42 Update COT Page
  content/platform/developer_guide/commitment_of_traders.mdx
  content/platform/user_guides/commitments_of_traders.mdx
  content/platform/user_guides/extensions.mdx
Labels: documentation

#43 [Platform] Remove GitHub Container Registry Reference From Install
  content/platform/installation.mdx
Labels: bug, documentation
